export const types = {

    START_LOADING: 'START_LOADING',
    STOP_LOADING: 'STOP_LOADING',

    GET_QUESTIONNAIRE_REQUEST: 'GET_QUESTIONNAIRE_REQUEST',
    GET_QUESTIONNAIRE_SUCCESS: 'GET_QUESTIONNAIRE_SUCCESS',
    GET_QUESTIONNAIRE_FAILURE: 'GET_QUESTIONNAIRE_FAILURE',
   
    GET_ORG_RESPONSES_REQUEST: 'GET_ORG_RESPONSES_REQUEST',
    GET_ORG_RESPONSES_SUCCESS: 'GET_ORG_RESPONSES_SUCCESS',
    GET_ORG_RESPONSES_FAILURE: 'GET_ORG_RESPONSES_FAILURE',

    GET_STATES_REQUEST: 'GET_STATES_REQUEST',
    GET_STATES_SUCCESS: 'GET_STATES_SUCCESS',
    GET_STATES_FAILURE: 'GET_STATES_FAILURE',

    SET_STATE_REQUEST: 'SET_STATE_REQUEST',

    SET_ORG_REQUEST: 'SET_ORG_REQUEST',
}