export const types = {
    
    START_TRACKER: 'START_TRACKER',
    STOP_TRACKER: 'STOP_TRACKER',

    INIT_TIME: 'INIT_TIME',
    INCREMENT_TIME: 'INCREMENT_TIME',

    SET_ACTIVITY_LEVEL: 'SET_ACTIVITY_LEVEL',

    GET_TASKS_REQUEST: 'GET_TASKS_REQUEST',
    GET_TASKS_SUCCESS: 'GET_TASKS_SUCCESS',
    GET_TASKS_FAILURE: 'GET_TASKS_FAILURE',

    CREATE_ACTIVITY_REQUEST: 'CREATE_ACTIVITY_REQUEST',
    CREATE_ACTIVITY_SUCCESS: 'CREATE_ACTIVITY_SUCCESS',
    CREATE_ACTIVITY_FAILURE: 'CREATE_ACTIVITY_FAILURE',

    UPDATE_ACTIVITY_REQUEST: 'UPDATE_ACTIVITY_REQUEST',
    UPDATE_ACTIVITY_SUCCESS: 'UPDATE_ACTIVITY_SUCCESS',
    UPDATE_ACTIVITY_FAILURE: 'UPDATE_ACTIVITY_FAILURE',

    GET_ACTIVITY_REQUEST: 'GET_ACTIVITY_REQUEST',
    GET_ACTIVITY_SUCCESS: 'GET_ACTIVITY_SUCCESS',
    GET_ACTIVITY_FAILURE: 'GET_ACTIVITY_FAILURE',
}