export const types = {
	CURRENT_AUTHENTICATED_USER_REQUEST: 'CURRENT_AUTHENTICATED_USER_REQUEST',
	CURRENT_AUTHENTICATED_USER_SUCCESS: 'CURRENT_AUTHENTICATED_USER_SUCCESS',
	CURRENT_AUTHENTICATED_USER_FAILURE: 'CURRENT_AUTHENTICATED_USER_FAILURE',

	CURRENT_USER_POOL_REQUEST: 'CURRENT_USER_POOL_REQUEST',
	CURRENT_USER_POOL_SUCCESS: 'CURRENT_USER_POOL_SUCCESS',
	CURRENT_USER_POOL_FAILURE: 'CURRENT_USER_POOL_FAILURE',

	PROFILE_INFO_REQUEST: 'PROFILE_INFO_REQUEST',
	PROFILE_INFO_SUCCESS: 'PROFILE_INFO_SUCCESS',
	PROFILE_INFO_FAILURE: 'PROFILE_INFO_FAILURE',

	FEDERATED_SIGN_IN_REQUEST: 'FEDERATED_SIGN_IN_REQUEST',
	FEDERATED_SIGN_IN_SUCCESS: 'FEDERATED_SIGN_IN_SUCCESS',
	FEDERATED_SIGN_IN_FAILURE: 'FEDERATED_SIGN_IN_FAILURE',

	SIGN_IN_USER_REQUEST: 'SIGN_IN_USER_REQUEST',
	SIGN_IN_USER_SUCCESS: 'SIGN_IN_USER_SUCCESS',
	SIGN_IN_USER_FAILURE: 'SIGN_IN_USER_FAILURE',

	LOGOUT_USER_REQUEST: 'LOGOUT_USER_REQUEST',
	LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',
	LOGOUT_USER_FAILURE: 'LOGOUT_USER_FAILURE',

	REDIRECT_REQUEST: 'REDIRECT_REQUEST',
	CLEAN_REDIRECT_REQUEST: 'CLEAN_REDIRECT_REQUEST',
};
